### PR TITLE
Sprint 2 first week

### PR DESCRIPTION
**Pull request by nicoloboo02**
# Description

This pull request includes all the features that have been implemented during the first week of Sprint 2

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Screenshot(If applies):

### CODE REVIEW

**Comment by sebasruii** [comment]
None of the buttons on the sidebar that are supposed to render a creation modal work the way they are expected.
image
`Dar de alta` and `Añadir elemento` take you to the Family and Food listing respectively, but do not summon the modal.
Still, those creation modals do appear if you click on the green button next to the sidebar in each listing page.

**Comment by nicoloboo02** [comment]
Good afternoon @sebasruii , I think that in spite of this, the changes have to be made to main as it is not such a serious error, which can be solved in the future. I await your opinion, thanks!

**Review by sebasruii — APPROVED** [review]
Good afternoon @nicoloboo02, I agree with you and after trying out the feature, no panics are prompted, so I think this is ready to go!

**Review by Ronald752 — APPROVED** [review]
I have checked that everything is working properly. So I think it's ready to go. Good work.

**Pull request merged**
