### PR TITLE
feat: emergency button email for CyC

### LINKED ISSUE #79: feat: Emergency Button
## Feature Description
Emergency button functionality is to be created and added.
## Motivation
This has to be done so that, in case users are unable to access the application, they can have our help.
## Acceptance Criteria
- [ ] [Criteria 1: The button redirects you to an explanatory page.]
- [ ] [Criteria 2: An email is sent requesting assistance.]

### PR DESCRIPTION
**Pull request by Marchabar**
# Description

I have added the feature so when an user in the login page clicks  on the emergency button besides "Iniciar Sesión" an email is sent to harmonyltd@outlook.es saying that it is ont possible to access the CyC system. This has been done using Sendgrid.

PLEASE DO NOT SPAM THE EMERGENCY BUTTON, BECAUSE WE HAVE A LIMITED NUMBER OF REQUESTS WITH THE BASIC PLAN OF SENDGRID. 

A warning appears in the backend respository because for this feature I am using next js server, so the backend does not know where that requests come from when clicking into the button. You should not worry about this since the whole system is  working perfectly anyways.

- You should make pip install since there is a new package for sendgrid
- Also you should add in the .env the following (ask Marchabar for the values):
   - SENDGRID_API_KEY= askMarchabar
   - EMAIL_USER= askMarchabar

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Screenshot(If applies):
image
image
image

### CODE REVIEW

**Review by JMGarCas — COMMENTED** [review]
Hello Marco. I have been trying your feature and I think that there are some aspects that must be improved:

- I expected some sort of confirmation mechanism when you click the button. It's quite easy to mistakenly click it instead of the login one.
- I also expected some sort of explanation when clicking the button of what it actually does. You could solve this at the same time as the previous one.
- The email is sent into the spam inbox. Is there a way to avoid this?

**Comment by TunixR** [comment]
imagen

Jose Miguel refers to a confirmation like this

**Comment by Marchabar** [comment]
> Hello Marco. I have been trying your feature and I think that there are some aspects that must be improved:
> 
> * I expected some sort of confirmation mechanism when you click the button. It's quite easy to mistakenly click it instead of the login one.
> * I also expected some sort of explanation when clicking the button of what it actually does. You could solve this at the same time as the previous one.
> * The email is sent into the spam inbox. Is there a way to avoid this?

I have fixed it!
image
About the spam, I was not able to find anything to make it work properly, but the email sending is working perfectly.

**Comment by JMGarCas** [comment]
> > Hello Marco. I have been trying your feature and I think that there are some aspects that must be improved:
> > 
> > * I expected some sort of confirmation mechanism when you click the button. It's quite easy to mistakenly click it instead of the login one.
> > * I also expected some sort of explanation when clicking the button of what it actually does. You could solve this at the same time as the previous one.
> > * The email is sent into the spam inbox. Is there a way to avoid this?
> 
> I have fixed it! image About the spam, I was not able to find anything to make it work properly, but the email sending is working perfectly.

Great, I have tested it and works correctly, good job!

**Review by JMGarCas — APPROVED** [review]
Good job!

**Pull request merged**
