### PR TITLE
Feature/4 families listing screen

### PR DESCRIPTION
**Pull request by JaviGarc1a**
# Description

I have modified both layout.js and page.js to .jsx as it should be because we are working with React. I have also made the families list screen. Changed search bar components to add filter and "submit" buttons, added in sidebar z-20, because the search bar was put on top. The tags for age ranges and deliveries are missing, but backend has not provided the data yet.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Screenshot:

image

### CODE REVIEW

**Comment by Ronald752** [comment]
The merge must be performed to the develop branch.

**Comment by JaviGarc1a** [comment]
Changed

**Comment by JaviGarc1a** [comment]
If it is all right with you, the tests can be performed now.
 
image

**Review by Ronald752 — APPROVED** [review]
The family list is displayed correctly with the given specifications, good work. I will now proceed with testing.

**Comment by Ronald752** [comment]
Tests have passed successfully with 100% coverage.

image

**Pull request merged**
