### PR TITLE
Feature/3 creation of initial components

### PR DESCRIPTION
**Pull request by nicoloboo02**
# Description

Sidebar, Searchbar and Modal components have been created, to be used as a base for the rest of the project.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by JMGarCas** [comment]
Buenas Nicolás, en general los componentes están bien pero hay detalles que tienen que ser arreglados:

Un error general es que se han utilizado archivos CSS y valores absolutos a la hora de aplicar estilos, esto hay que cambiarlo para futuras versiones a tailwind y hacerlo responsive.

Otro error es que ha creado una carpeta "static" para los archivos estáticos. En Next.js, estos archivos se guardan en la carpeta "public" la cual se creó al inicializar el proyecto.

=== Sidebar ===

- IMPORTANTE: Cambiar el elemento <a> a <Link>, propio de Next.js: https://nextjs.org/docs/pages/api-reference/components/link. Primer video de midu para más detalles.

- IMPORTANTE: Cambiar el elemento  a <Image>, propio de Next.js: https://nextjs.org/docs/pages/api-reference/components/image. Primer video de midu para más detalles.

- El hover de las entradas no es el mismo que el de los mockups:
imagen
Figura 1: Hover del mockup
Captura
Figura 2: Hover desarrollado

- Al hace hover sobre una entrada, se produce layout shift. Me imagino que es porque al hacer hover, se forma un border que ocupa espacio. Aquí te dejo dos posibles soluciones:
- - Propiedad box-sizing de CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
- - Reservar espacio para un div blanco al lado de la entrada, que al hacer hover a la misma se vuelve azul.

- El botón de cerrar sesión no es como el del mockup. Tiene que tener la letra blanca y un icono representativo.

- Entre el botón de cerrar sesión y las entradas tiene que haber una línea como en el mockup. Propongo usar hr de HTML.

=== Searchbar ===

- Falta un icono como en el mockup, esto se puede hacer con un truco visual. Mire los inputs de mi Login Screen para ver como se hace.

=== Modal ===

- Esta bien. Me gusta que se aplique blur al fondo cuando está abierto y que puedas cerrarlo pinchando fuera. Buen trabajo.

**Comment by JMGarCas** [comment]
También añadir que no es necesario BrowserRouter de 'react-router-dom', elimine esta dependencia para que el proyecto sea mas ligero.

**Comment by JMGarCas** [comment]
Good afternoon Nicolás, overall the components are fine but there are details that need to be fixed:

A general bug is that you have used CSS files and absolute values when applying styles, this needs to be changed for future versions to tailwind and it also must be responsive.

Another bug is that you have created a "static" folder for static files. In Next.js, these files are stored in the "public" folder which was created when initializing the project.

=== Sidebar ===

- IMPORTANT: Change the HTML element anchor (a) to (Link), proper of Next.js: https://nextjs.org/docs/pages/api-reference/components/link. First midudev's video for more details.

- IMPORTANT: Change the HTML element (img) to (Image), proper of Next.js: https://nextjs.org/docs/pages/api-reference/components/image. First midudev's video for more details.

- The hover of the inputs is not the same as the one of the mockups:

- When hovering over an input, there is layout shifting. I imagine that happens because when hovering, it produces a border that occupies space. Here are two possible solutions:
- - CSS box-sizing property: https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
- - Reserve space for a white div next to the input, which turns blue when hovering.

- The logout button is not like the one in the mockup. It has to have the white font and a representative icon.

- Between the logout button and the inputs there has to be a line as in the mockup. I propose to use HTML element hr.

=== Searchbar ===

- Compared to the mockup, an icon is missing. Maybe you did not know how to put an icon inside an input. It can be done with a visual trick. Look at my Login Screen inputs to see how it is done.

=== Modal ===

- It's ok. I like that blur is applied to the background when it is open and you can close it by clicking outside. Good job.

**Comment by nicoloboo02** [comment]
Good afternoon Josemi, changes made, hopefully this time definitive. The files, honestly, I had completely forgotten to pass them on, thanks for reminding me again.
Regards!

**Comment by JMGarCas** [comment]
I have no more complaints, great job!

**Review by JMGarCas — APPROVED** [review]
Good job!

**Pull request merged**
