### PR TITLE
Feature/96 pilot user feedback

### LINKED ISSUE #96: feat: Pilot user feedback
## Feature Description
Add feedback from pilot users
## Acceptance Criteria
- [x] [Criteria 1: They want that in order to eliminate a family, the family has to be deregistered.]
- [x] [Criteria 2: They want to import and export families from Excel.]
- [x] [Criteria 3: The age of the family members must be shown.]
## Additional Details
[Add any other relevant details about the proposed feature]

### PR DESCRIPTION
**Pull request by sebasruii**
# Description

I have made the changes requested by the pilot users as requested in #96.
## Delete families
The option to delete a family now only appears if the family is Suspended. I have updated the options, so now a user can quickly suspend a family through the "Dar de baja" option:
image

After a family is suspended, the options are changed, now allowing the user to re-activate or delete the family. The option to add a new delivery is also removed, only being showed if the family is active. I've also added a text indicating that the family is currently Suspended
image

When clicking on the delete button, the user is promted with a confirmation window to avoid mistakes
image

## Members age
I've added the age (in years) of each family member through a function that takes into account their birthdate (thanks ChatGPT)
image

## Export family data
I've fixed family data export functionality. I have not updated import URL since it is not currently implemented.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

closes #96

### CODE REVIEW

**Review by TunixR — CHANGES_REQUESTED** [review]
imagen
This "Edades" should include the age intervals of the family. Remember the intervals are: `0-3, 4-15, 16-45, 46-60, 60+`

This "X" button should be removed if it is not to be used
imagen

**Comment by sebasruii** [comment]
I updated (and forgot to mention on the PR description) the functionality for the x button. Before it was used to delete a family, and now it serves as a way to close the family detail page an return to the family listing, which I think makes more sense given its symbol. Kind of like a button to close a modal.

Regarding the "Edades" field, I will make the changes as you requested 👍🏻

**Comment by TunixR** [comment]
> I updated (and forgot to mention on the PR description) the functionality for the x button. Before it was used to delete a family, and now it serves as a way to close the family detail page an return to the family listing, which I think makes more sense given its symbol. Kind of like a button to close a modal.

To me it feels out of place, it is the only button like that in the application and its not very descriptive being right next to the edit button. It looks like a delete button even though I know it isn't

**Comment by sebasruii** [comment]
image
Now age groups are displayed as a set of tags depending on the members ages

**Review by TunixR — APPROVED** [review]
Looks good to me now

**Pull request merged**
