### PR TITLE
Feat/75 feat error handling

### LINKED ISSUE #75: feat: Error Handling
## Feature Description
All errors should be handled so that when the user gets an error, it is more descriptive.
## Acceptance Criteria
- [ ] [Criteria 1: The errors are fully descriptive of why they jump out

### PR DESCRIPTION
**Pull request by TunixR**
# Description

This pr includes validation for the following forms.
- Family create & update
- Warehouse
- Food Update (only the form part) and Create
- Delivery create (Page refreshes after confirming but validations should work. They can be seen right before it refreshes)
- Create and edit user
- Login

# How Has This Been Tested?

No tests have yet been conducted

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by JMGarCas — COMMENTED** [review]
Hello Antonio. I have been testing your feature and there are some ascpects that do not work correctly:
- There is a fatal error if you put 00000000R as the nid of an user when creating a family.
- I can not create a warehouse, there is a fatal error. I can not look at the error because the page refreshs.
- When creating an user, if the password confirmation is not the same as the password, a warning is shown, as expected. However, if this is fixed, you can still see the warning.
- When creating an element, there will be an error when:
- - The number of kg is 0
- - The date is not specified
- - The date is earlier than now

**Comment by TunixR** [comment]
It should all be fixed now. Thank you for the review

**Comment by TunixR** [comment]
I cannot fix the create a warehouse thing. I did not do it and Im not yet familiar with that part of the code. Maybe a new issue should be opened

**Review by JMGarCas — COMMENTED** [review]
Indeed, it now works correctly, good job!

**Review by JMGarCas — APPROVED** [review]
Good job.

**Pull request merged**
