### PR TITLE
Join new components

### PR DESCRIPTION
**Pull request by JaviGarc1a**
# Description

App has been made fully responsive and refactored. Every single component has been modified. Everyone should check that your newest features has been correctly implemented. Otherwise, let us know about it with a detailed explanation of what is the issue and how to fix it.

# How Has This Been Tested?

Testing informal.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by nicoloboo02 — APPROVED** [review]
Incredible work, it works properly.

**Review by sebasruii — CHANGES_REQUESTED** [review]
Great work, everything looks great. There is one thing that needs to be fixed:
image
The attribute name and ID for "Hermandad o asociación" must be named `referred_organization` in order for the API to accept post requests.

**Review by sebasruii — APPROVED** [review]
Outstanding work. Congratulations to both! 🥳

**Review by Ronald752 — APPROVED** [review]
good job

**Review by Manuelgruiz — APPROVED** [review]
Looks amazing!

**Pull request merged**
